#------------------------------------------------------------------------------#
# This makefile was generated by 'cbp2make' tool rev.147                       #
#------------------------------------------------------------------------------#


WORKDIR = %cd%

CC = gcc.exe
CXX = g++.exe
AR = ar.exe
LD = g++.exe
WINDRES = windres.exe

INC = -ID:\\SFML\\SFML-2.0\\include
CFLAGS = -Wall
RESINC = 
LIBDIR = -LD:\\SFML\\SFML-2.0\\lib
LIB = 
LDFLAGS = -static -static-libgcc

INC_DEBUG = $(INC)
CFLAGS_DEBUG = $(CFLAGS) -g
RESINC_DEBUG = $(RESINC)
RCFLAGS_DEBUG = $(RCFLAGS)
LIBDIR_DEBUG = $(LIBDIR)
LIB_DEBUG = $(LIB)D:\SFML\SFML-2.0\lib\libsfml-audio-d.a D:\SFML\SFML-2.0\lib\libsfml-graphics-d.a D:\SFML\SFML-2.0\lib\libsfml-main-d.a D:\SFML\SFML-2.0\lib\libsfml-network-d.a D:\SFML\SFML-2.0\lib\libsfml-system-d.a D:\SFML\SFML-2.0\lib\libsfml-window-d.a
LDFLAGS_DEBUG = $(LDFLAGS)
OBJDIR_DEBUG = obj\\Debug
DEP_DEBUG = 
OUT_DEBUG = bin\\Debug\\KursSFML2.exe

INC_RELEASE = $(INC)
CFLAGS_RELEASE = $(CFLAGS) -O2
RESINC_RELEASE = $(RESINC)
RCFLAGS_RELEASE = $(RCFLAGS)
LIBDIR_RELEASE = $(LIBDIR)
LIB_RELEASE = $(LIB)D:\SFML\SFML-2.0\lib\libsfml-audio.a D:\SFML\SFML-2.0\lib\libsfml-graphics.a D:\SFML\SFML-2.0\lib\libsfml-main.a D:\SFML\SFML-2.0\lib\libsfml-network.a D:\SFML\SFML-2.0\lib\libsfml-system.a D:\SFML\SFML-2.0\lib\libsfml-window.a
LDFLAGS_RELEASE = $(LDFLAGS) -s
OBJDIR_RELEASE = obj\\Release
DEP_RELEASE = 
OUT_RELEASE = bin\\Release\\KursSFML2.exe

OBJ_DEBUG = $(OBJDIR_DEBUG)\\main.o $(OBJDIR_DEBUG)\\chequer.o $(OBJDIR_DEBUG)\\blockContainer.o $(OBJDIR_DEBUG)\\block.o $(OBJDIR_DEBUG)\\Menu.o

OBJ_RELEASE = $(OBJDIR_RELEASE)\\main.o $(OBJDIR_RELEASE)\\chequer.o $(OBJDIR_RELEASE)\\blockContainer.o $(OBJDIR_RELEASE)\\block.o $(OBJDIR_RELEASE)\\Menu.o

all: debug release

clean: clean_debug clean_release

before_debug: 
	cmd /c if not exist bin\\Debug md bin\\Debug
	cmd /c if not exist $(OBJDIR_DEBUG) md $(OBJDIR_DEBUG)

after_debug: 

debug: before_debug out_debug after_debug

out_debug: before_debug $(OBJ_DEBUG) $(DEP_DEBUG)
	$(LD) $(LIBDIR_DEBUG) -o $(OUT_DEBUG) $(OBJ_DEBUG)  CC = gcc $(LDFLAGS_DEBUG) $(LIB_DEBUG)

$(OBJDIR_DEBUG)\\main.o: main.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c main.cpp -o $(OBJDIR_DEBUG)\\main.o

$(OBJDIR_DEBUG)\\chequer.o: chequer.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c chequer.cpp -o $(OBJDIR_DEBUG)\\chequer.o

$(OBJDIR_DEBUG)\\blockContainer.o: blockContainer.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c blockContainer.cpp -o $(OBJDIR_DEBUG)\\blockContainer.o

$(OBJDIR_DEBUG)\\block.o: block.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c block.cpp -o $(OBJDIR_DEBUG)\\block.o

$(OBJDIR_DEBUG)\\Menu.o: Menu.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c Menu.cpp -o $(OBJDIR_DEBUG)\\Menu.o

clean_debug: 
	cmd /c del /f $(OBJ_DEBUG) $(OUT_DEBUG)
	cmd /c rd bin\\Debug
	cmd /c rd $(OBJDIR_DEBUG)

before_release: 
	cmd /c if not exist bin\\Release md bin\\Release
	cmd /c if not exist $(OBJDIR_RELEASE) md $(OBJDIR_RELEASE)

after_release: 

release: before_release out_release after_release

out_release: before_release $(OBJ_RELEASE) $(DEP_RELEASE)
	$(LD) $(LIBDIR_RELEASE) -o $(OUT_RELEASE) $(OBJ_RELEASE)  $(LDFLAGS_RELEASE) -mwindows $(LIB_RELEASE)

$(OBJDIR_RELEASE)\\main.o: main.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c main.cpp -o $(OBJDIR_RELEASE)\\main.o

$(OBJDIR_RELEASE)\\chequer.o: chequer.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c chequer.cpp -o $(OBJDIR_RELEASE)\\chequer.o

$(OBJDIR_RELEASE)\\blockContainer.o: blockContainer.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c blockContainer.cpp -o $(OBJDIR_RELEASE)\\blockContainer.o

$(OBJDIR_RELEASE)\\block.o: block.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c block.cpp -o $(OBJDIR_RELEASE)\\block.o

$(OBJDIR_RELEASE)\\Menu.o: Menu.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c Menu.cpp -o $(OBJDIR_RELEASE)\\Menu.o

clean_release: 
	cmd /c del /f $(OBJ_RELEASE) $(OUT_RELEASE)
	cmd /c rd bin\\Release
	cmd /c rd $(OBJDIR_RELEASE)

.PHONY: before_debug after_debug clean_debug before_release after_release clean_release

